# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e1e719aa6c91ba07e2f6732ce65f7610daf00d24a992dbac6d3ab49061e86924b27c0a3a708bc8b31dd0ac300a44be989456cd9e85316cbf1232a0473a9c168

test:
  secret_key_base: be098e6c95a19618c8ebd65f061e7a8cf35b8430e1d3170f9d395a5953a90a19ff42a6ffa2213100d000f815485ba5f6235be0ddc12c7341c7403364a2aa6ad3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
